apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-svc-deployment
  labels:
    app: account-service-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: account-service  
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
      - name: account-service-container
        image: bhaskarvdocker/account-service:latest 
        ports:
        - containerPort: 8080           
